<?php if(!defined("ABSPATH"))exit;
$data=tc_pricing_data();$months=array(1,3,6,12);$verda=array();foreach($months as $t){$v=tc_pricing_rate('H100',$t,$data);if($v!==null)$verda[$t]=$v;}
if(count($verda)<4||empty($data['gpus']['H100']['base_usd']))return;
$gpu=$data['gpus']['H100'];$checked=tc_pricing_date($data);$source=isset($data['source_url'])?$data['source_url']:'https://verda.com/pricing';
// Columns: on-demand, then commitment terms. Equal spacing by category (see methodology).
$cols=array('0'=>'On-demand','1'=>'1 month','3'=>'3 months','6'=>'6 months','12'=>'12 months');
$series=array();$points=array();$flat=array();$offscale=array();
$series[]=array('key'=>'verda','name'=>'Verda','color'=>'#176858','width'=>3,'url'=>$source,'values'=>array('0'=>(float)$gpu['base_usd'])+array_combine(array_map('strval',array_keys($verda)),array_values($verda)),'note'=>'calculated from published base + discounts');
$palette=array('together'=>'#a35d2a','hyperstack'=>'#3b5f8a','lambda'=>'#7a5c9e','azure'=>'#5f6f7a');
foreach(array('together','hyperstack','lambda','azure') as $key){
 $p=tc_pricing_provider($key,$data);if(!$p||empty($p['gpus']['H100']['on_demand_usd']))continue;
 $h=$p['gpus']['H100'];$color=isset($palette[$key])?$palette[$key]:'#61766a';
 if(!empty($p['tier'])&&$p['tier']==='hyperscaler'){$offscale[]=array('name'=>$p['name'],'model'=>$h['model'],'od'=>(float)$h['on_demand_usd'],'terms'=>(array)($h['term_rates']??array()),'url'=>$p['source_url']);continue;}
 $vals=array('0'=>(float)$h['on_demand_usd']);foreach((array)($h['term_rates']??array()) as $m=>$r){if(isset($cols[(string)$m]))$vals[(string)$m]=(float)$r;}
 if(count($vals)>1)$series[]=array('key'=>$key,'name'=>$p['name'],'color'=>$color,'width'=>2.5,'url'=>$p['source_url'],'values'=>$vals,'buckets'=>(array)($h['term_buckets']??array()),'note'=>'published reserved rates by duration bucket');
 else $points[]=array('key'=>$key,'name'=>$p['name'],'color'=>$color,'url'=>$p['source_url'],'value'=>$vals['0']);
 if(!empty($h['reserved_from_usd']))$flat[]=array('name'=>$p['name'],'color'=>$color,'value'=>(float)$h['reserved_from_usd']);
}
$all=array();foreach($series as $s)foreach($s['values'] as $v)$all[]=$v;foreach($points as $pt)$all[]=$pt['value'];foreach($flat as $f)$all[]=$f['value'];
$lo=floor((min($all)-0.05)*10)/10;$hi=ceil((max($all)+0.05)*10)/10;if($hi-$lo<0.4){$hi=$lo+0.4;}
$w=500;$h_svg=300;$top=52;$bottom=$h_svg-58;$left=52;$right=470;$n=count($cols);$xs=array();$i=0;foreach(array_keys($cols) as $c){$xs[$c]=$left+16+$i*(($right-$left-32)/($n-1));$i++;}
$y=function($v)use($lo,$hi,$top,$bottom){return $top+($hi-$v)/($hi-$lo)*($bottom-$top);};
$label='H100 price per GPU-hour by commitment term. ';foreach($series as $s){$parts=array();foreach($s['values'] as $c=>$v)$parts[]=$cols[$c].' '.number_format($v,$c==='0'?2:4);$label.=$s['name'].': '.implode(', ',$parts).'. ';}
foreach($points as $pt)$label.=$pt['name'].' on-demand '.number_format($pt['value'],2).', no term schedule published. ';
foreach($flat as $f)$label.=$f['name'].' reserved from '.number_format($f['value'],2).', term not published. ';
$label.=sprintf('Vertical axis runs from %s to %s dollars and does not start at zero.',number_format($lo,1),number_format($hi,1));
$ticks=array($hi,$lo+($hi-$lo)*2/3,$lo+($hi-$lo)/3,$lo);
?><figure class="editorial-chart"><div class="chart-kicker"><span>H100 COMMITMENT CURVES</span><span>USD / GPU-hour</span></div><svg viewBox="0 0 <?php echo (int)$w; ?> <?php echo (int)$h_svg; ?>" role="img" aria-label="<?php echo esc_attr($label); ?>"><?php
foreach($ticks as $tick){$py=round($y($tick),2);echo '<line x1="'.$left.'" y1="'.esc_attr($py).'" x2="'.$right.'" y2="'.esc_attr($py).'" stroke="#d7e2df"/><text x="'.($left-8).'" y="'.esc_attr($py+4).'" text-anchor="end">'.esc_html(number_format($tick,1)).'</text>';}
echo '<line x1="'.esc_attr($xs['0']+(($xs['1']-$xs['0'])/2)).'" y1="'.$top.'" x2="'.esc_attr($xs['0']+(($xs['1']-$xs['0'])/2)).'" y2="'.$bottom.'" stroke="#c5d2cb" stroke-dasharray="3 4"/>';
foreach($cols as $c=>$name)echo '<text x="'.esc_attr(round($xs[$c],2)).'" y="'.($h_svg-30).'" text-anchor="middle">'.esc_html($name).'</text>';
foreach($flat as $f){$py=round($y($f['value']),2);echo '<line x1="'.$left.'" y1="'.esc_attr($py).'" x2="'.$right.'" y2="'.esc_attr($py).'" stroke="'.esc_attr($f['color']).'" stroke-width="1.5" stroke-dasharray="2 4"><title>'.esc_html($f['name'].' reserved from '.tc_pricing_usd($f['value'],2).' (term not published)').'</title></line>';}
foreach($series as $s){$pts=array();foreach($s['values'] as $c=>$v)$pts[]=round($xs[$c],2).','.round($y($v),2);echo '<polyline points="'.esc_attr(implode(' ',$pts)).'" fill="none" stroke="'.esc_attr($s['color']).'" stroke-width="'.esc_attr($s['width']).'" stroke-linejoin="round"/>';}
foreach($series as $s){$last=array_key_last($s['values']);foreach($s['values'] as $c=>$v){$px=round($xs[$c],2);$py=round($y($v),2);echo '<circle cx="'.esc_attr($px).'" cy="'.esc_attr($py).'" r="4.5" fill="'.esc_attr($s['color']).'"><title>'.esc_html($s['name'].' · '.$cols[$c].' · '.tc_pricing_usd($v,$c==='0'?2:4)).'</title></circle>';
 if($c===$last){echo '<text class="value" style="fill:'.esc_attr($s['color']).'" x="'.esc_attr($px+8).'" y="'.esc_attr($py+4).'" text-anchor="start">'.esc_html(tc_pricing_usd($v,2)).'</text>';}}}
foreach($points as $pt){$px=round($xs['0'],2);$py=round($y($pt['value']),2);$crowded=false;foreach($series as $s){if(abs($s['values']['0']-$pt['value'])<0.18)$crowded=true;}$ty=$crowded?$py+17:$py+4;$tx=$crowded?$px-6:$px+8;echo '<circle cx="'.esc_attr($px).'" cy="'.esc_attr($py).'" r="4.5" fill="#f0f5f1" stroke="'.esc_attr($pt['color']).'" stroke-width="2.5"><title>'.esc_html($pt['name'].' on-demand '.tc_pricing_usd($pt['value'],2).' (no term schedule published)').'</title></circle><text class="value" style="fill:'.esc_attr($pt['color']).'" x="'.esc_attr($tx).'" y="'.esc_attr($ty).'" text-anchor="start">'.esc_html($pt['name'].' '.tc_pricing_usd($pt['value'],2)).'</text>';}
?></svg><div class="chart-legend"><?php foreach($series as $s):$first=$s['values']['0'];$lastv=$s['values'][array_key_last($s['values'])]; ?><span><i style="--c:<?php echo esc_attr($s['color']); ?>"></i><?php echo esc_html($s['name']); ?> · <?php echo esc_html(tc_pricing_usd($first,2)); ?> on-demand → <?php echo esc_html(tc_pricing_usd($lastv,2)); ?> at <?php echo esc_html(strtolower($cols[array_key_last($s['values'])])); ?></span><?php endforeach;foreach($points as $pt): ?><span><i class="dot" style="--c:<?php echo esc_attr($pt['color']); ?>"></i><?php echo esc_html($pt['name']); ?> · on-demand only</span><?php endforeach;foreach($flat as $f): ?><span><i style="--c:<?php echo esc_attr($f['color']); ?>;--d:dotted"></i><?php echo esc_html($f['name'].' · reserved from '.tc_pricing_usd($f['value'],2).' (term not published)'); ?></span><?php endforeach; ?></div><figcaption>Verda · <?php echo esc_html($gpu['model'].' '.$gpu['vram_gb'].'GB'); ?> · Checked <?php echo esc_html($checked); ?> · Calculated from <a href="<?php echo esc_url($source); ?>">published base + discounts</a>.<?php foreach($series as $s):if($s['key']==='verda')continue; ?> <a href="<?php echo esc_url($s['url']); ?>"><?php echo esc_html($s['name']); ?></a> · published reserved rates<?php if(!empty($s['buckets'])): ?> by duration bucket (<?php $b=array();foreach($s['buckets'] as $m=>$txt)$b[]=esc_html($txt).' → '.esc_html($cols[(string)$m]);echo implode(', ',$b); ?>)<?php endif; ?>.<?php endforeach; ?><?php foreach($points as $pt): ?> <a href="<?php echo esc_url($pt['url']); ?>"><?php echo esc_html($pt['name']); ?></a> · on-demand only; no term schedule published.<?php endforeach; ?><?php foreach($offscale as $o): ?><br>Off this scale: <a href="<?php echo esc_url($o['url']); ?>"><?php echo esc_html($o['name']); ?></a> <?php echo esc_html($o['model']); ?>, per GPU: <?php echo esc_html(tc_pricing_usd($o['od'],2)); ?> on-demand<?php foreach($o['terms'] as $m=>$r): ?>, <?php echo esc_html(tc_pricing_usd((float)$r,2)); ?> at <?php echo esc_html(((int)$m)%12===0?((int)$m/12).'-year':$m.'-month'); ?><?php endforeach; ?>.<?php endforeach; ?><br>Equal spacing by category; connecting lines are guides, not prices for unlisted terms. Configurations, regions, networking and tax treatment differ; see the buyer guide before comparing.</figcaption></figure>
