<?php get_header(); ?>
<main id="main" class="home"><div class="edition-line"><span>THE COMPUTE BRIEF</span><span><?php echo esc_html(strtoupper(wp_date('j F Y'))); ?></span></div><?php tc_topics(); ?>
<section class="lead-grid"><article class="lead-story"><?php
$featured=absint(get_theme_mod('tc_featured_post',0));$args=array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>1,'ignore_sticky_posts'=>true);
if($featured&&get_post_status($featured)==='publish'&&get_post_type($featured)==='post')$args['p']=$featured;
$lead=new WP_Query($args);$lead_id=0;if($lead->have_posts()):while($lead->have_posts()):$lead->the_post();$lead_id=get_the_ID();tc_category(); ?>
<h1><a href="<?php the_permalink(); ?>"><?php if(get_post_meta(get_the_ID(),'_tc_sample_slug',true)==='two-clocks-of-gpu-rental' && get_the_title()==='The two clocks behind every GPU rental quote'): ?>The two clocks<br>behind every<br><em>GPU rental quote.</em><?php else:the_title();endif; ?></a></h1><p><?php echo esc_html(get_the_excerpt()); ?></p><?php tc_meta(); ?><a class="read-link" href="<?php the_permalink(); ?>">Read the guide ↗</a>
<?php endwhile;else: ?><span class="category">GPU RENTAL ECONOMICS</span><h1>Understanding<br>the cost<br><em>of compute.</em></h1><p>GPU rental pricing, contract durations and future capacity. Our first guides are being prepared.</p><?php endif;wp_reset_postdata(); ?></article><div class="feature-figure"><?php get_template_part('template-parts/curve'); ?><p class="figure-context">A longer commitment and a later start are separate pricing decisions.</p></div></section>
<section class="latest"><div class="section-heading"><h2>Understand before you commit.</h2><a href="<?php echo esc_url(tc_guides_url()); ?>">All guides ↗</a></div><div class="story-grid"><?php $recent=new WP_Query(array('post_type'=>'post','post_status'=>'publish','posts_per_page'=>3,'post__not_in'=>$lead_id?array($lead_id):array(),'ignore_sticky_posts'=>true));if($recent->have_posts()):while($recent->have_posts()):$recent->the_post();tc_card();endwhile;else: ?><p class="empty-state">New guides will appear here as they are published.</p><?php endif;wp_reset_postdata(); ?></div></section>
<?php if($lead_id)tc_ad('home');$pricing=tc_page_url('pricing');if($pricing): ?>
<section class="lab-feature"><div><span class="category">THE PRICING LAB</span><h2>See the two time axes<br>working together.</h2><p>Explore published commitment discounts and see which future-start prices remain unavailable.</p><a class="button" href="<?php echo esc_url($pricing); ?>">Explore the data ↗</a></div><?php get_template_part('template-parts/mini-table'); ?></section><?php endif; ?>
<section class="editor-note"><span class="category">OUR APPROACH</span><h2>The conditions behind the number matter.</h2><p>Contract terms, sources and comparison assumptions belong alongside the price. The Pricing Lab distinguishes published inputs, calculated rates and missing forward-start observations.</p><?php if($url=tc_page_url('editorial-policy')): ?><a class="read-link" href="<?php echo esc_url($url); ?>">Read our editorial policy ↗</a><?php endif; ?></section>
<?php if(is_page()):while(have_posts()):the_post();if(trim(get_the_content())): ?><section class="prose home-content"><?php the_content(); ?></section><?php endif;endwhile;endif; ?>
</main><?php get_footer(); ?>
