<?php
/* Template Name: GPU Price Tracker */
get_header();
$gpu=tc_tracker_gpu();$meta=tc_tracker_gpus()[$gpu];$data=tc_pricing_data();$checked=tc_pricing_date($data);$rows=tc_tracker_rows($gpu,$data);$hist=tc_tracker_series($gpu);$days=count($hist['dates']);
$term_cols=array();foreach($rows as $r)foreach($r['terms'] as $m=>$v)$term_cols[(string)$m]=1;ksort($term_cols,SORT_NUMERIC);$term_cols=array_keys($term_cols);
$term_label=function($m){$m=(int)$m;return $m>=12&&$m%12===0?($m/12).' yr':$m.' mo';};
$fmt=function($v,$d=2){return $v===null?'—':tc_pricing_usd($v,$d);};
while(have_posts()):the_post(); ?>
<main id="main" class="info-page tracker"><div class="breadcrumbs"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a> / <?php the_title(); ?></div>
<div class="tracker-head"><div><span class="category">PRICE TRACKER · UPDATED DAILY</span><h1><?php the_title(); ?></h1><p class="tracker-lede"><?php echo esc_html($meta['name']); ?> rental prices per GPU-hour from suppliers that publish them, collected automatically every day. Last source check <strong><?php echo esc_html($checked); ?></strong> (UTC).</p></div><div class="tracker-snapshot"><span>SOURCES CHECKED</span><strong><?php echo esc_html($checked); ?></strong><small><?php echo esc_html($days); ?> day<?php echo $days===1?'':'s'; ?> of history</small></div></div>
<nav class="tracker-tabs" aria-label="GPU"><?php foreach(tc_tracker_gpus() as $key=>$g):$u=tc_tracker_url($key);if(!$u)continue; ?><a href="<?php echo esc_url($u); ?>"<?php echo $key===$gpu?' aria-current="page"':''; ?>><?php echo esc_html($key); ?></a><?php endforeach; ?></nav>
<?php if(trim(get_post_field('post_content',get_the_ID()))): ?><div class="prose tracker-intro"><?php the_content(); ?></div><?php endif; ?>
<?php $glance=tc_tracker_glance($gpu);if($glance): ?><section class="tracker-section tracker-glance"><h2>At a glance · <?php echo esc_html($checked); ?></h2><ul><?php foreach($glance as $line): ?><li><?php echo esc_html($line); ?></li><?php endforeach; ?></ul><p class="tracker-note">Sentences are generated from the current snapshot and the collected history; they change when the data changes.</p></section><?php endif; ?>
<?php if(!$rows): ?><p class="empty-state">No published prices are being tracked for this GPU yet.</p><?php else: ?>
<section class="tracker-section"><h2>Published prices by supplier</h2><div class="table-scroll"><table class="tracker-table"><thead><tr><th>Supplier</th><th>Configuration</th><th class="num">On-demand</th><th class="num">Spot</th><?php foreach($term_cols as $m): ?><th class="num"><?php echo esc_html($term_label($m)); ?></th><?php endforeach; ?><th>Basis</th></tr></thead><tbody>
<?php foreach($rows as $r): ?><tr class="<?php echo esc_attr('tier-'.$r['tier'].(strpos($r['status'],'ok')===0?'':' stale')); ?>"><td><a href="<?php echo esc_url($r['url']); ?>" rel="nofollow noopener"><?php echo esc_html($r['name']); ?> ↗</a><?php if(strpos($r['status'],'ok')!==0): ?><small>last good <?php echo esc_html($r['checked_on']); ?></small><?php endif; ?></td><td class="config"><?php echo esc_html($r['model']); ?><small><?php echo esc_html($r['unit']); ?></small></td><td class="num"><?php echo esc_html($fmt($r['on_demand'])); ?></td><td class="num"><?php echo esc_html($fmt($r['spot'])); ?></td><?php foreach($term_cols as $m): ?><td class="num"><?php echo isset($r['terms'][$m])?esc_html($fmt($r['terms'][$m],$r['kind']==='calculated'?4:2)):'—'; ?></td><?php endforeach; ?><td class="basis"><span class="data-tag <?php echo esc_attr($r['kind']); ?>"><?php echo $r['kind']==='calculated'?'Calculated':'Published'; ?></span><?php if($r['reserved_from']!==null): ?><small>Reserved from <?php echo esc_html($fmt($r['reserved_from'])); ?>, term not published</small><?php endif; ?><small><?php echo esc_html($r['term_note']); ?></small></td></tr><?php endforeach; ?>
</tbody></table></div><p class="tracker-note">USD per GPU-hour. “—” means not published by that supplier. Azure figures are the VM price divided by eight GPUs and, for reservations, the total divided by the term’s hours. Configurations, regions, networking, storage, minimum quantities and taxes differ; a lower hourly figure is not a cost-per-job verdict.</p></section>
<section class="tracker-section"><h2>Commitment curves</h2><div class="tracker-chart"><?php get_template_part('template-parts/curve',null,array('gpu'=>$gpu)); ?></div></section>
<section class="tracker-section"><h2>On-demand price history</h2><div class="tracker-chart"><?php get_template_part('template-parts/history',null,array('gpu'=>$gpu,'series'=>$hist)); ?></div></section>
<?php endif; ?>
<section class="tracker-section prose"><h2>Data and downloads</h2><p>Every daily observation is published as <a href="<?php echo esc_url(tc_pricing_download_url('json')); ?>">JSON</a> and <a href="<?php echo esc_url(tc_pricing_download_url('csv')); ?>">CSV</a>, and the full day-by-day history is kept in the <a href="https://github.com/tensorcurve/web/blob/main/tensorcurve/assets/data/pricing-history.csv">public repository</a>. Collection rules, validation and comparison limits are described in the <?php if($u=tc_page_url('methodology')): ?><a href="<?php echo esc_url($u); ?>">data methodology</a><?php else: ?>data methodology<?php endif; ?>.<?php if($u=tc_page_url('pricing')): ?> Explore commitment terms interactively in the <a href="<?php echo esc_url($u); ?>">Pricing Lab</a>.<?php endif; ?></p></section>
</main>
<?php endwhile;get_footer(); ?>
