<?php
/* Template Name: Pricing Lab (Published Tariffs) */
get_header();
if(post_password_required()){ ?><main id="main" class="info-page"><?php echo get_the_password_form(); ?></main><?php }else{ ?><div class="lab-shell"><main id="main"><div class="page-heading"><div><div class="eyebrow">COMPUTE / RENTAL MARKETS</div><h1>GPU Pricing Lab<span class="accent">.</span></h1><p>Explore commitment terms and future start dates in one view.</p></div><div class="snapshot"><span>SOURCE CHECKED</span><strong>13 Sep 2026 <small>· UTC</small></strong></div></div>
<div class="demo-banner"><span class="demo-icon">i</span><p><strong>Published inputs, calculated rates.</strong> Verda public tariff snapshot · 13 Sep 2026. Region and start availability unverified. <a href="https://verda.com/pricing">Official source ↗</a></p></div>
<section class="filters" aria-label="Pricing filters"><label>GPU model<select id="gpu"><option value="H100">NVIDIA H100</option><option value="H200">NVIDIA H200</option><option value="A100">NVIDIA A100</option></select></label><label>Region<select id="region"><option value="unspecified">Not specified by tariff</option></select></label><label>Start date<select id="start"><option value="0">Public tariff · No guaranteed start</option><option value="1">+1 month · Not published</option><option value="3">+3 months · Not published</option><option value="6">+6 months · Not published</option></select></label><label>Commitment term<select id="term"><option value="1">1 month</option><option value="3" selected>3 months</option><option value="6">6 months</option><option value="12">12 months</option></select></label><div class="configuration"><span>CONFIGURATION</span><strong>1 GPU <span>·</span> Verda instance</strong></div></section>
<section class="metrics" aria-label="Selected pricing summary" aria-live="polite"><article><span class="metric-label">Calculated term rate <span class="tag">SNAPSHOT</span></span><div class="metric-number" id="median"></div><small id="selection"></small></article><article><span class="metric-label">Discount vs. on-demand</span><div class="metric-number mint" id="discount"></div><small>Published commitment discount</small></article><article><span class="metric-label">Forward-start premium</span><div class="metric-number" id="premium"></div><small>No future-start prices in source</small></article><article><span class="metric-label">Modeled compute cost</span><div class="metric-number" id="contract"></div><small id="costnote"></small></article></section>
<section class="visuals"><article class="panel curve-panel"><div class="panel-title"><div><span class="eyebrow">01 / COMMITMENT</span><h2>Rental term structure</h2><p>One supplier · Published discount schedule</p></div><span class="unit">USD / GPU-hour</span></div><div id="curve" class="curve" role="img" aria-label="Calculated rental rates by commitment duration and future start date"></div><div class="legend"><span><i style="--color:#176858"></i>Calculated public tariff</span><span>Future starts: not published in dataset</span></div><div class="panel-note">Calculated from base × (1 − discount). Lines do not imply unlisted terms.</div></article>
<article class="panel surface-panel"><div class="panel-title"><div><span class="eyebrow">02 / FORWARD START</span><h2>Rental price surface</h2><p>Select a cell to compare that contract.</p></div><span class="tag">SNAPSHOT</span></div><div class="matrix-label">COMMITMENT TERM →</div><div id="matrix" class="matrix"></div><div class="heat-key"><span>Lower rate</span><div></div><span>Higher rate</span></div><div class="panel-note">*Tariff has no guaranteed start. — = Not published in dataset.</div></article></section>
<section class="panel quotes"><div class="panel-title"><div><span class="eyebrow">03 / PROVIDER COMPARISON</span><h2>Source record and calculated rate</h2><p id="quote-subtitle"></p></div><span class="count-badge">1 public source</span></div><div class="table-wrap"><table><caption class="sr-only">Tariff-derived rate for the selected GPU and term</caption><thead><tr><th>Provider</th><th>Start date</th><th>Term</th><th class="numeric">USD / GPU-hour</th><th class="numeric">Modeled total · 1 GPU</th><th>Data type</th></tr></thead><tbody id="quote-rows"></tbody></table></div><div class="table-footer"><span>Planning assumption: 720 hours/month × term × one GPU. Not an invoice.</span><span>No live availability</span></div></section>
<section id="methodology" class="methodology"><div><span class="eyebrow">READING THE DATA</span><h2>Two time axes.<br>One consistent comparison.</h2></div><div><h3>Start date ≠ contract duration</h3><p>Forward start is when usage begins. Commitment term is how long capacity is rented. A 3-month term starting today differs from one starting in three months.</p></div><div><h3>Explicit assumptions</h3><p>The public base and discount schedule determine each rate. Planning totals use one GPU × 720 hours/month × term. Extras are excluded; the result is not an invoice.</p></div></section>
<div class="lab-footer"><span>Source checked 13 Sep 2026 · No automatic refresh</span><a href="<?php echo esc_url(tc_page_url('methodology')?:home_url('/')); ?>">Methodology</a></div>
</main></div><?php }get_footer(); ?>